### PR TITLE
SSM Support

### PR DESCRIPTION
**Pull request by bdwyertech**
### Description

Add support for evaluating an EC2 instances status within the AWS Simple Systems Manager ecosystem.

### Issues Resolved

N/A

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [ ] All Unit Tests pass
- [ ] `rake lint` passes
- [ ] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by bdwyertech** [comment]
SSM Compliance is specific to EC2 resources.  Compliance/non-compliance is a characteristic of an EC2 instance.  I believe it should be part of the EC2 resource -- it is implemented this way in other tools like Cloud Custodian as well.

**Comment by rmoles** [comment]
> SSM Compliance is specific to EC2 resources. Compliance/non-compliance is a characteristic of an EC2 instance. I believe it should be part of the EC2 resource -- it is implemented this way in other tools like Cloud Custodian as well.

This is a fair point. Perhaps this is the best place for this resource to live. However, it does require integration and unit testing and finally some documentation before we are able to get this merged.

**Comment by bdwyertech** [comment]
Sure.  I'll give it a shot when I have some free time.

If anyone happens to stumble across this and is interested in doing this,
be my guest as I'm no expert in this area.

**Comment by rmoles** [comment]
Hi @bdwyertech, since there haven't been any updates on this PR and we have recently added functionality that covers SSM I am going to close this. Feel free to re-open the PR if necessary.
Thanks again for the work involved in raising the PR.

**Pull request closed without merging**
