### PR TITLE
Fix output

### PR DESCRIPTION
**Pull request by lvthillo**
### Description

Same issue as described here: https://github.com/inspec/inspec-aws/issues/387

### CODE REVIEW

**Review by soumyo13 — APPROVED** [review]
Thanks.

**Review by soumyo13 — APPROVED** [review]

**Comment by soumyo13** [comment]
Here in this PR the following is failing.

libraries/aws_ec2_transit_gateway_attachments.rb:8:1: C: [Correctable] Layout/TrailingWhitespace: Trailing whitespace detected.

The above issue is a linting issue. Please fix it and push.

**Comment by lvthillo** [comment]
@soumyo13 fixed the linting issue.

**Comment by soumyo13** [comment]
Thanks

**Comment by MaxCCC** [comment]
When will this be merged?

**Comment by soumyo13** [comment]
We are having some technical difficulties in merging this PR. So we created a new PR and merged to the master. Now these changes are there in the master branch. Please check.

**Comment by clintoncwolfe** [comment]
There still remains one case of using backticks as quotes, in aws_ec2_eips.rb .  Please check by running "grep 'example`' -rn lib" to search for other examples.

This is breaking the tests on the InSpec project.

**Comment by sathish-progress** [comment]
@clintoncwolfe this PR https://github.com/inspec/inspec-aws/pull/416 fixes that issue 

Closing this PR
cc: @lvthillo & @MaxCCC

**Pull request closed without merging**
