### PR TITLE
Fix aws_auto_scaling_groups tags handling

### PR DESCRIPTION
**Pull request by guilhermef**
Signed-off-by: Guilherme Souza <guilhermef@users.noreply.github.com>

### Description

The current implementation of `aws_auto_scaling_groups` is handling each tag as a new auto-scaling group entry.
I've fixed adding it as part of the auto-scaling group and added tests to ensure it matches the expected output.

### Issues Resolved

List any existing issues this PR resolves, or any Discourse or StackOverflow discussion that's relevant

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [ ] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [ ] Documentation provided or updated for resources 
- [ ] All Integration Tests pass
- [x] All Unit Tests pass
- [x] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by guilhermef** [comment]
Sorry to ping you directly @sathish-progress, but that's a bug on the resource usage.

**Comment by guilhermef** [comment]
Hi @IanMadd, that fixes an existing bug on the inspec-aws codebase.

**Comment by guilhermef** [comment]
That issue is still blocking us, is there anything I can do to get it merged?

**Review by sathish-progress — APPROVED** [review]
LGTM

**Pull request merged**
