### PR TITLE
soumyo/aws_iam_ssh_public_key

### LINKED ISSUE #689: AWS IAM SSH Keys age rotated within 730 days for AWS CodeCommit

### PR DESCRIPTION
**Pull request by soumyo13**
Signed-off-by: Soumyodeep Karmakar <soumyo.k13@gmail.com>

### Description

This resource pack contains the singular and plural resource. No Terraform available. 

### Issues Resolved

#689

### Check List
Please fill box or appropriate ([x]) or mark N/A.
- [x] New functionality includes integration tests/controls
- [ ] New Terraform resources
- [x] Documentation provided or updated for resources 
- [x] All Integration Tests pass
- [x] All Unit Tests pass
- [x] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

**Comment by soumyo13** [comment]
> Is there a resource available to get the ssh_public_key_id connected to the iam_ssh_public_key, in order to iterate through keys and check the properties? It seems like there would need to be a plural resource of aws_iam_ssh_public_key to iterate through all keys on the account.

I have added the plural resource.

**Comment by dkumaras** [comment]
> @Nirbhay1997 , @soumyo13 : The 'aws_iam_ssh_public_keys.md' file is not available in the said branch. Kindly advise how to proceed.

Its available now. Reviewed it.

**Comment by soumyo13** [comment]
> > @Nirbhay1997 , @soumyo13 : The 'aws_iam_ssh_public_keys.md' file is not available in the said branch. Kindly advise how to proceed.
> 
> Its available now. Reviewed it.

Thanks.

**Comment by jb897** [comment]
Hi, there is an issue in the plural resource file. Since there is no username specified in the username field for the API call, according to the AWS documentation "the UserName field is determined implicitly based on the AWS access key used to sign the request."
This is causing errors, as we are unable to iterate through all of the keys that are stored on the account. As seen in the screenshots below, when testing the plural resource, I am getting a failure of no keys existing, however when checking for the existence of an individual key I have created, it is shown as existing and passing the test. I believe the plural resource needs to have a parameter for the username for the IAM user to list SSH public keys for.
Screen Shot 2021-10-21 at 3 33 27 PM
Screen Shot 2021-10-21 at 3 32 53 PM

**Comment by soumyo13** [comment]
> > The plural resource uses the API "list_ssh_public_keys" which does not have a required parameter "user_ name". So the attribute "user_name" is not mandatory. Even I have tested the same and it worked fine for me.
> > 
> > Link to the API: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/IAM/Client.html#list_ssh_public_keys-instance_method
> > 
> > image
> > @jb897 We can provide the "user_name" attribute as a required parameter. Please let me know.
> 
> Thank you so much for understanding. I would greatly appreciate adding in user_name as a required parameter or as an optional parameter, since it is not required for the API. Whatever is best in your opinion.
> 
> 

Great. We will do that.

**Review by soumyo13 — COMMENTED** [review]
@dkumaras Please review it again.

**Comment by soumyo13** [comment]
@jb897 -> I have added the plural resource. I made the "user_name" the optional parameter. If the user wants to pass the username, he/she can pass it. Just done according to his need. Please check the documentation for more information.

**Review by dkumaras — APPROVED** [review]

**Pull request merged**
