### PR TITLE
Correct documentation of aws_dynamodb_table

### PR DESCRIPTION
**Pull request by rgevaert**
The example for aws_dynamodb_table is wrong.

### CODE REVIEW

**Comment by skpaterson** [comment]
Apologies, before merging @rgevaert we need a DCO as per https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco

**Comment by rgevaert** [comment]
I see there are some other issues with the docs now I'm adding my tests ;). I'll add some more commits

**Comment by rgevaert** [comment]
I think I should have catched all of them

**Comment by rgevaert** [comment]
Is there a way to see the generated html? The markdown is still ok in my markdown viewer.

**Comment by skpaterson** [comment]
Any valid markdown should resolve correctly.   Thanks again for these improvements!

**Pull request merged**
